import React from 'react';
import { QuizProvider } from '../contexts/QuizContext';
import ExamInterface from '../components/ExamInterface';
import { Question } from '../contexts/QuizContext';

const mockQuestions: Question[] = [
  {
    id: 1,
    type: 'mcq',
    subject: 'Physics',
    content: 'A projectile is launched from the ground with an initial velocity of 100 m/s at an angle of 45° to the horizontal. What is the maximum height reached? (Take g = 10 m/s²)',
    options: [
      '250 m',
      '500 m',
      '750 m',
      '1000 m',
    ],
    correctAnswer: '250 m',
    userAnswer: null,
    marked: false,
  },
  {
    id: 2,
    type: 'assertion-reason',
    subject: 'Physics',
    assertion: 'The resistance of a conductor increases with temperature.',
    reason: 'This is because the thermal motion of atoms increases, leading to more collisions with electrons.',
    correctAnswer: 'A is true, R is true; R is correct explanation',
    userAnswer: null,
    marked: false,
  },
  {
    id: 3,
    type: 'mcq',
    subject: 'Chemistry',
    content: 'Which of the following is not a noble gas?',
    options: [
      'Helium',
      'Neon',
      'Argon',
      'Nitrogen',
    ],
    correctAnswer: 'Nitrogen',
    userAnswer: null,
    marked: false,
  },
  {
    id: 4,
    type: 'mcq',
    subject: 'Chemistry',
    content: 'The pH of pure water at 25°C is:',
    options: [
      '6',
      '7',
      '8',
      '9',
    ],
    correctAnswer: '7',
    userAnswer: null,
    marked: false,
  },
  {
    id: 5,
    type: 'assertion-reason',
    subject: 'Chemistry',
    assertion: 'CO2 is acidic in nature.',
    reason: 'CO2 dissolves in water to form carbonic acid.',
    correctAnswer: 'A is true, R is true; R is correct explanation',
    userAnswer: null,
    marked: false,
  },
  {
    id: 6,
    type: 'mcq',
    subject: 'Math',
    content: 'What is the derivative of sin(x)?',
    options: [
      'cos(x)',
      '-cos(x)',
      'sin(x)',
      '-sin(x)',
    ],
    correctAnswer: 'cos(x)',
    userAnswer: null,
    marked: false,
  },
  {
    id: 7,
    type: 'mcq',
    subject: 'Math',
    content: 'The value of ∫₀¹ x² dx is:',
    options: [
      '1/2',
      '1/3',
      '1/4',
      '1/5',
    ],
    correctAnswer: '1/3',
    userAnswer: null,
    marked: false,
  },
  {
    id: 8,
    type: 'assertion-reason',
    subject: 'Math',
    assertion: 'Every continuous function on a closed interval attains its maximum and minimum values.',
    reason: 'This is the Extreme Value Theorem.',
    correctAnswer: 'A is true, R is true; R is correct explanation',
    userAnswer: null,
    marked: false,
  },
  {
    id: 9,
    type: 'mcq',
    subject: 'Physics',
    content: 'What is the SI unit of force?',
    options: [
      'Dyne',
      'Newton',
      'Joule',
      'Watt',
    ],
    correctAnswer: 'Newton',
    userAnswer: null,
    marked: false,
  },
  {
    id: 10,
    type: 'mcq',
    subject: 'Physics',
    content: 'The speed of light in vacuum is approximately:',
    options: [
      '3 × 10⁸ m/s',
      '3 × 10⁹ m/s',
      '3 × 10⁷ m/s',
      '3 × 10¹⁰ m/s',
    ],
    correctAnswer: '3 × 10⁸ m/s',
    userAnswer: null,
    marked: false,
  },
  {
    id: 11,
    type: 'mcq',
    subject: 'Chemistry',
    content: 'What is the atomic number of oxygen?',
    options: [
      '6',
      '7',
      '8',
      '9',
    ],
    correctAnswer: '8',
    userAnswer: null,
    marked: false,
  },
  {
    id: 12,
    type: 'mcq',
    subject: 'Chemistry',
    content: 'Which compound is a strong acid?',
    options: [
      'Acetic acid',
      'Hydrochloric acid',
      'Carbonic acid',
      'Sulfurous acid',
    ],
    correctAnswer: 'Hydrochloric acid',
    userAnswer: null,
    marked: false,
  },
  {
    id: 13,
    type: 'mcq',
    subject: 'Math',
    content: 'What is the sum of angles in a triangle?',
    options: [
      '90°',
      '180°',
      '270°',
      '360°',
    ],
    correctAnswer: '180°',
    userAnswer: null,
    marked: false,
  },
  {
    id: 14,
    type: 'mcq',
    subject: 'Math',
    content: 'Solve: 2x + 5 = 13',
    options: [
      'x = 2',
      'x = 3',
      'x = 4',
      'x = 5',
    ],
    correctAnswer: 'x = 4',
    userAnswer: null,
    marked: false,
  },
  {
    id: 15,
    type: 'assertion-reason',
    subject: 'Physics',
    assertion: 'An object in uniform circular motion is in equilibrium.',
    reason: 'The net force on the object is zero.',
    correctAnswer: 'A is false, R is false',
    userAnswer: null,
    marked: false,
  },
  {
    id: 16,
    type: 'mcq',
    subject: 'Chemistry',
    content: 'What is the oxidation state of sulfur in H2SO4?',
    options: [
      '+4',
      '+5',
      '+6',
      '+7',
    ],
    correctAnswer: '+6',
    userAnswer: null,
    marked: false,
  },
  {
    id: 17,
    type: 'mcq',
    subject: 'Physics',
    content: 'The SI unit of electrical charge is:',
    options: [
      'Coulomb',
      'Ampere',
      'Volt',
      'Ohm',
    ],
    correctAnswer: 'Coulomb',
    userAnswer: null,
    marked: false,
  },
  {
    id: 18,
    type: 'mcq',
    subject: 'Math',
    content: 'What is the value of log₁₀(100)?',
    options: [
      '1',
      '2',
      '10',
      '100',
    ],
    correctAnswer: '2',
    userAnswer: null,
    marked: false,
  },
  {
    id: 19,
    type: 'assertion-reason',
    subject: 'Chemistry',
    assertion: 'NaCl is an ionic compound.',
    reason: 'Sodium and chlorine have a large difference in electronegativity.',
    correctAnswer: 'A is true, R is true; R is correct explanation',
    userAnswer: null,
    marked: false,
  },
  {
    id: 20,
    type: 'mcq',
    subject: 'Math',
    content: 'What is the area of a circle with radius 5?',
    options: [
      '25π',
      '10π',
      '15π',
      '30π',
    ],
    correctAnswer: '25π',
    userAnswer: null,
    marked: false,
  },
];

const ExamPage: React.FC = () => {
  return (
    <QuizProvider initialQuestions={mockQuestions} totalTime={3600}>
      <ExamInterface />
    </QuizProvider>
  );
};

export default ExamPage;
